apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: pizza-prometheus
    url: http://prometheus:9090
    isDefault: false
    editable: true
    jsonData:
      timeInterval: 5s
